# Generated by Django 4.2.14 on 2024-09-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['dep_name'],
            },
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.IntegerField()),
                ('s2', models.IntegerField()),
                ('s3', models.IntegerField()),
                ('s4', models.IntegerField()),
                ('s5', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='s_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='s_fathername',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='s_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='s_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='report.department'),
        ),
        migrations.AddField(
            model_name='main',
            name='s_score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sco', to='report.score'),
        ),
    ]
