# Generated by Django 4.2.14 on 2024-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_department_score_main_s_email_main_s_fathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='s_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
