# Generated by Django 4.2.14 on 2024-09-20 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_alter_main_s_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20, null=True)),
                ('s_fathername', models.CharField(max_length=20, null=True)),
                ('s_email', models.EmailField(max_length=254, null=True)),
                ('s_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep', to='report.department')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.RemoveField(
            model_name='score',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='s3',
        ),
        migrations.RemoveField(
            model_name='score',
            name='s4',
        ),
        migrations.RemoveField(
            model_name='score',
            name='s5',
        ),
        migrations.DeleteModel(
            name='main',
        ),
    ]
