# Generated by Django 4.2.14 on 2024-09-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_card_subject_remove_score_s1_remove_score_s2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='s_dep',
            new_name='Student_Department',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='s_email',
            new_name='Student_Email',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='s_fathername',
            new_name='Student_Father_Name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='s_name',
            new_name='Student_Name',
        ),
        migrations.AddField(
            model_name='score',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.card'),
        ),
        migrations.AddField(
            model_name='score',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.subject'),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
