# Generated by Django 4.2.14 on 2024-09-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_department_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.subject'),
        ),
    ]
