# Generated by Django 4.2.14 on 2024-09-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_score_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('Student', 'Subject')},
        ),
    ]
